<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Modality;
use App\Models\Player;
use App\Models\Position;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PlayersSeeder extends Seeder
{
    public function run(): void
    {
        // ─── 60 Male Players + 20 Female Players ───
        $malePlayers = $this->getMalePlayers();
        $femalePlayers = $this->getFemalePlayers();
        $allPlayers = array_merge($malePlayers, $femalePlayers);

        foreach ($allPlayers as $index => $data) {
            // Create user
            $user = User::create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make('password'),
                'email_verified_at' => now()->subDays(rand(1, 365)),
                'role' => 'player',
                'status' => 'active',
                'avatar_path' => $data['photo'],
                'locale' => $data['locale'] ?? 'en',
                'timezone' => $data['timezone'] ?? 'UTC',
                'last_login_at' => now()->subDays(rand(0, 14)),
                'created_at' => now()->subDays(rand(30, 365)),
            ]);

            // Resolve country IDs
            $nationality = Country::where('code', $data['nationality_code'])->first();
            $birthplaceCountry = Country::where('code', $data['birthplace_country_code'] ?? $data['nationality_code'])->first();

            // Calculate age & minor flag
            $dob = $data['dob'];
            $age = now()->diffInYears($dob);
            $isMinor = $age < 18;

            // Create player profile
            $player = Player::create([
                'user_id' => $user->id,
                'full_name' => $data['name'],
                'nickname' => $data['nickname'] ?? null,
                'slug' => Str::slug($data['name']) . '-' . $user->id,
                'date_of_birth' => $dob,
                'gender' => $data['gender'],
                'height_cm' => $data['height'],
                'weight_kg' => $data['weight'] ?? null,
                'preferred_foot' => $data['foot'],
                'nationality_country_id' => $nationality->id,
                'birthplace_country_id' => $birthplaceCountry->id,
                'birthplace_city' => $data['birthplace_city'],
                'current_club' => $data['current_club'],
                'team_since' => $data['team_since'],
                'agent_name' => $data['agent'] ?? null,
                'is_minor' => $isMinor,
                'guardian_name' => $isMinor ? $data['guardian_name'] ?? null : null,
                'guardian_relationship' => $isMinor ? ($data['guardian_relationship'] ?? 'Father') : null,
                'guardian_email' => $isMinor ? $data['guardian_email'] ?? null : null,
                'profile_photo_path' => $data['photo'],
                'video_url' => $data['video_url'],
                'description' => $data['description'],
                'profile_status' => $data['status'] ?? 'published',
                'is_featured' => $data['featured'] ?? false,
                'is_verified' => $data['verified'] ?? false,
                'published_at' => now()->subDays(rand(7, 180)),
                'created_at' => $user->created_at,
            ]);

            // Attach positions
            $positionIds = Position::whereIn('code', $data['positions'])->pluck('id', 'code');
            foreach ($data['positions'] as $i => $code) {
                $player->positions()->attach($positionIds[$code], [
                    'is_primary' => $i === 0,
                ]);
            }

            // Attach modalities
            $modalityIds = Modality::whereIn('code', $data['modalities'])->pluck('id');
            $player->modalities()->attach($modalityIds);
        }

        $this->command->info('✓ Created ' . count($allPlayers) . ' player profiles (60 male, 20 female)');
    }

    /**
     * 60 male players with realistic data and real photos.
     * Photos source: pravatar.cc with gender-locked seeds (men)
     */
    private function getMalePlayers(): array
    {
        return [
            // ─── Brazilian Players (priority country) ───
            [
                'name' => 'Benjamin Silva',
                'nickname' => 'Benja',
                'email' => 'benjamin.silva@example.com',
                'dob' => '2009-01-30',
                'gender' => 'male',
                'height' => 178,
                'weight' => 71,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_country_code' => 'BRA',
                'birthplace_city' => 'Rio de Janeiro',
                'current_club' => 'Anápolis Sub-15',
                'team_since' => '2025-03-01',
                'agent' => 'Talentos S/A',
                'guardian_name' => 'Carlos Silva',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'carlos.silva@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=11',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['ST', 'LW'],
                'modalities' => ['football', 'futsal', 'beach_soccer'],
                'description' => 'Fast, focused player with exceptional game vision and strong ball control. Comfortable in tight spaces, confident in 1v1 situations. Strong aerial ability and excellent positioning inside the box.',
                'featured' => true,
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Gabriel Santos',
                'nickname' => 'Gabi',
                'email' => 'gabriel.santos@example.com',
                'dob' => '2008-06-15',
                'gender' => 'male',
                'height' => 181,
                'weight' => 74,
                'foot' => 'left',
                'nationality_code' => 'BRA',
                'birthplace_country_code' => 'BRA',
                'birthplace_city' => 'São Paulo',
                'current_club' => 'Santos FC B',
                'team_since' => '2024-08-01',
                'photo' => 'https://i.pravatar.cc/400?img=12',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CAM', 'CM'],
                'modalities' => ['football'],
                'description' => 'Creative attacking midfielder with elite passing range. Reads the game two steps ahead. Strong on set pieces with both feet.',
                'featured' => true,
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Lucas Ferreira',
                'nickname' => 'Lukas',
                'email' => 'lucas.ferreira@example.com',
                'dob' => '2005-09-22',
                'gender' => 'male',
                'height' => 188,
                'weight' => 82,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_country_code' => 'BRA',
                'birthplace_city' => 'Belo Horizonte',
                'current_club' => 'Cruzeiro EC',
                'team_since' => '2023-07-01',
                'photo' => 'https://i.pravatar.cc/400?img=13',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['CB', 'LB'],
                'modalities' => ['football'],
                'description' => 'Tall, commanding centre-back. Dominant in aerial duels and clean in possession. Reads passes well and recovers quickly.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'João Pedro Costa',
                'nickname' => 'JP',
                'email' => 'joao.costa@example.com',
                'dob' => '2009-04-18',
                'gender' => 'male',
                'height' => 175,
                'weight' => 68,
                'foot' => 'both',
                'nationality_code' => 'BRA',
                'birthplace_country_code' => 'BRA',
                'birthplace_city' => 'Salvador',
                'current_club' => 'Bahia Sub-17',
                'team_since' => '2024-02-15',
                'agent' => 'Sports Future',
                'guardian_name' => 'Maria Costa',
                'guardian_relationship' => 'Mother',
                'guardian_email' => 'maria.costa@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=14',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CM', 'CDM'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Two-footed midfielder with excellent ball retention. Great work rate, presses from the front and tracks back. Captain material.',
                'featured' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Matheus Oliveira',
                'nickname' => 'Math',
                'email' => 'matheus.oliveira@example.com',
                'dob' => '2007-11-03',
                'gender' => 'male',
                'height' => 184,
                'weight' => 78,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Curitiba',
                'current_club' => 'Athletico Paranaense',
                'team_since' => '2023-09-01',
                'photo' => 'https://i.pravatar.cc/400?img=15',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'Clinical finisher with both feet. 18 goals in last 24 youth matches. Strong hold-up play, brings teammates into attacks.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Rafael Almeida',
                'email' => 'rafael.almeida@example.com',
                'dob' => '2006-08-12',
                'gender' => 'male',
                'height' => 192,
                'weight' => 85,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Porto Alegre',
                'current_club' => 'Grêmio FBPA',
                'team_since' => '2024-01-10',
                'photo' => 'https://i.pravatar.cc/400?img=16',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['GK'],
                'modalities' => ['football'],
                'description' => 'Goalkeeper with exceptional reflexes and command of the area. Excellent shot-stopper, distributes long and short with precision.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Pedro Henrique Rocha',
                'nickname' => 'Pedrinho',
                'email' => 'pedro.rocha@example.com',
                'dob' => '2010-02-28',
                'gender' => 'male',
                'height' => 168,
                'weight' => 60,
                'foot' => 'left',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Fortaleza',
                'current_club' => 'Fortaleza EC Sub-15',
                'team_since' => '2025-01-15',
                'agent' => 'Brazil Sports Agency',
                'guardian_name' => 'Roberto Rocha',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'roberto.rocha@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=33',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['LW', 'CAM'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Skillful left-footer who loves to take defenders on. Quick feet, low centre of gravity. Compared to a young Neymar by youth coaches.',
                'featured' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Bruno Carvalho',
                'email' => 'bruno.carvalho@example.com',
                'dob' => '2007-05-19',
                'gender' => 'male',
                'height' => 179,
                'weight' => 73,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Recife',
                'current_club' => 'Náutico',
                'team_since' => '2024-06-01',
                'photo' => 'https://i.pravatar.cc/400?img=51',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['RB', 'RW'],
                'modalities' => ['football'],
                'description' => 'Modern attacking right-back. Strong overlapping runs, good crossing. Tracks back diligently and tackles cleanly.',
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Felipe Martins',
                'nickname' => 'Felipão',
                'email' => 'felipe.martins@example.com',
                'dob' => '2008-12-08',
                'gender' => 'male',
                'height' => 186,
                'weight' => 79,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Brasília',
                'current_club' => 'Brasiliense',
                'team_since' => '2024-03-20',
                'photo' => 'https://i.pravatar.cc/400?img=52',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CDM', 'CB'],
                'modalities' => ['football'],
                'description' => 'Defensive midfielder who shields the back four. Strong tackling, excellent positional awareness, calm in possession.',
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Vinícius Lima',
                'nickname' => 'Vini',
                'email' => 'vinicius.lima@example.com',
                'dob' => '2009-09-14',
                'gender' => 'male',
                'height' => 172,
                'weight' => 65,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Manaus',
                'current_club' => 'Manaus FC Sub-17',
                'team_since' => '2025-02-01',
                'guardian_name' => 'Ana Lima',
                'guardian_relationship' => 'Mother',
                'guardian_email' => 'ana.lima@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=53',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['RW', 'ST'],
                'modalities' => ['football', 'beach_soccer'],
                'description' => 'Lightning-quick winger. Beats defenders with pace and direct running. Improving final-third decision-making with every game.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],

            // ─── Argentine Players ───
            [
                'name' => 'Diego Fernández',
                'nickname' => 'Dieguito',
                'email' => 'diego.fernandez@example.com',
                'dob' => '2007-03-25',
                'gender' => 'male',
                'height' => 174,
                'weight' => 70,
                'foot' => 'left',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Buenos Aires',
                'current_club' => 'River Plate Reserve',
                'team_since' => '2024-01-05',
                'photo' => 'https://i.pravatar.cc/400?img=54',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CAM', 'ST'],
                'modalities' => ['football'],
                'description' => 'Classic Argentine number 10. Vision, technique, and a left foot that delivers in the final third. Free-kick specialist.',
                'featured' => true,
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Mateo Rodríguez',
                'email' => 'mateo.rodriguez@example.com',
                'dob' => '2008-07-11',
                'gender' => 'male',
                'height' => 183,
                'weight' => 76,
                'foot' => 'right',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Rosario',
                'current_club' => 'Newell\'s Old Boys',
                'team_since' => '2024-09-01',
                'photo' => 'https://i.pravatar.cc/400?img=55',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'Composed centre-back. Strong physical presence, excellent in the air. Comfortable bringing the ball out of defence.',
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Tomás García',
                'email' => 'tomas.garcia@example.com',
                'dob' => '2006-10-30',
                'gender' => 'male',
                'height' => 176,
                'weight' => 72,
                'foot' => 'right',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Córdoba',
                'current_club' => 'Talleres',
                'team_since' => '2023-08-15',
                'photo' => 'https://i.pravatar.cc/400?img=56',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['CM', 'CAM'],
                'modalities' => ['football'],
                'description' => 'Box-to-box midfielder with excellent stamina. Reads the game well, contributes goals from second line.',
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Santiago López',
                'nickname' => 'Santi',
                'email' => 'santiago.lopez@example.com',
                'dob' => '2009-05-07',
                'gender' => 'male',
                'height' => 170,
                'weight' => 63,
                'foot' => 'left',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Mendoza',
                'current_club' => 'Godoy Cruz',
                'team_since' => '2025-01-20',
                'guardian_name' => 'Pablo López',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'pablo.lopez@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=57',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['LW'],
                'modalities' => ['football'],
                'description' => 'Direct, fearless left winger. Skilful in 1v1 situations. Still developing physically but the talent is undeniable.',
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Nicolás Morales',
                'nickname' => 'Nico',
                'email' => 'nicolas.morales@example.com',
                'dob' => '2005-12-19',
                'gender' => 'male',
                'height' => 189,
                'weight' => 83,
                'foot' => 'right',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'La Plata',
                'current_club' => 'Estudiantes',
                'team_since' => '2023-03-10',
                'photo' => 'https://i.pravatar.cc/400?img=58',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['GK'],
                'modalities' => ['football'],
                'description' => 'Tall, agile goalkeeper. Excellent shot-stopper and commanding presence in the box. Distribution improving rapidly.',
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],

            // ─── Portuguese Players ───
            [
                'name' => 'André Pereira',
                'email' => 'andre.pereira@example.com',
                'dob' => '2007-04-14',
                'gender' => 'male',
                'height' => 180,
                'weight' => 75,
                'foot' => 'right',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Porto',
                'current_club' => 'FC Porto B',
                'team_since' => '2024-07-01',
                'photo' => 'https://i.pravatar.cc/400?img=59',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['CM', 'CDM'],
                'modalities' => ['football'],
                'description' => 'Technical Portuguese midfielder trained in the FC Porto academy. Smart positioning, range of passing impressive for his age.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],
            [
                'name' => 'Miguel Sousa',
                'email' => 'miguel.sousa@example.com',
                'dob' => '2008-08-22',
                'gender' => 'male',
                'height' => 177,
                'weight' => 71,
                'foot' => 'right',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Lisbon',
                'current_club' => 'Sporting CP B',
                'team_since' => '2024-08-15',
                'photo' => 'https://i.pravatar.cc/400?img=60',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['RW', 'CAM'],
                'modalities' => ['football'],
                'description' => 'Sporting academy product. Quick winger with end product. Cuts inside well, finishes with the inside of his left foot.',
                'featured' => true,
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],
            [
                'name' => 'Rui Tavares',
                'email' => 'rui.tavares@example.com',
                'dob' => '2009-11-09',
                'gender' => 'male',
                'height' => 185,
                'weight' => 76,
                'foot' => 'right',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Braga',
                'current_club' => 'SC Braga U17',
                'team_since' => '2025-02-10',
                'guardian_name' => 'José Tavares',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'jose.tavares@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=61',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'Tall, physical striker. Great in the air, holds the ball up well. Top scorer in Braga youth league this season with 14 goals.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],
            [
                'name' => 'Tiago Ramos',
                'email' => 'tiago.ramos@example.com',
                'dob' => '2006-06-17',
                'gender' => 'male',
                'height' => 182,
                'weight' => 77,
                'foot' => 'left',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Coimbra',
                'current_club' => 'Académica',
                'team_since' => '2023-12-01',
                'photo' => 'https://i.pravatar.cc/400?img=62',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['LB'],
                'modalities' => ['football'],
                'description' => 'Modern left-back with serious attacking instincts. Strong crossing ability, fits into a back three or back four system.',
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],

            // ─── Spanish Players ───
            [
                'name' => 'Pablo Hernández',
                'email' => 'pablo.hernandez@example.com',
                'dob' => '2008-02-04',
                'gender' => 'male',
                'height' => 175,
                'weight' => 69,
                'foot' => 'right',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Madrid',
                'current_club' => 'Real Madrid Castilla',
                'team_since' => '2024-06-30',
                'photo' => 'https://i.pravatar.cc/400?img=63',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['CAM', 'CM'],
                'modalities' => ['football'],
                'description' => 'La Fábrica graduate. Composed in tight spaces, exceptional vision. Drives play forward with purpose.',
                'featured' => true,
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],
            [
                'name' => 'Sergio Martínez',
                'email' => 'sergio.martinez@example.com',
                'dob' => '2007-09-26',
                'gender' => 'male',
                'height' => 187,
                'weight' => 80,
                'foot' => 'right',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Barcelona',
                'current_club' => 'FC Barcelona Juvenil A',
                'team_since' => '2024-08-01',
                'photo' => 'https://i.pravatar.cc/400?img=64',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'La Masia centre-back. Comfortable on the ball, plays out from the back with confidence. Strong leadership qualities.',
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],
            [
                'name' => 'Álvaro Ruiz',
                'email' => 'alvaro.ruiz@example.com',
                'dob' => '2006-12-11',
                'gender' => 'male',
                'height' => 178,
                'weight' => 73,
                'foot' => 'right',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Seville',
                'current_club' => 'Real Betis B',
                'team_since' => '2023-09-20',
                'photo' => 'https://i.pravatar.cc/400?img=65',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['CM'],
                'modalities' => ['football'],
                'description' => 'Andalusian midfielder with elegance on the ball. Press-resistant, finds passes others don\'t see.',
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],
            [
                'name' => 'Javier Castro',
                'nickname' => 'Javi',
                'email' => 'javier.castro@example.com',
                'dob' => '2009-07-03',
                'gender' => 'male',
                'height' => 168,
                'weight' => 61,
                'foot' => 'left',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Valencia',
                'current_club' => 'Valencia CF Juvenil',
                'team_since' => '2025-01-15',
                'guardian_name' => 'Carmen Castro',
                'guardian_relationship' => 'Mother',
                'guardian_email' => 'carmen.castro@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=66',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['LW', 'ST'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Pacy left winger with futsal background. Phenomenal close control, scores spectacular goals.',
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],

            // ─── French Players ───
            [
                'name' => 'Hugo Lefèvre',
                'email' => 'hugo.lefevre@example.com',
                'dob' => '2007-01-15',
                'gender' => 'male',
                'height' => 184,
                'weight' => 78,
                'foot' => 'right',
                'nationality_code' => 'FRA',
                'birthplace_city' => 'Paris',
                'current_club' => 'Paris Saint-Germain U19',
                'team_since' => '2024-07-15',
                'photo' => 'https://i.pravatar.cc/400?img=67',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'Physical, modern striker. Holds the ball up, brings teammates in. Has the killer instinct in the box.',
                'featured' => true,
                'verified' => true,
                'locale' => 'fr',
                'timezone' => 'Europe/Paris',
            ],
            [
                'name' => 'Mathis Bernard',
                'email' => 'mathis.bernard@example.com',
                'dob' => '2008-04-28',
                'gender' => 'male',
                'height' => 181,
                'weight' => 74,
                'foot' => 'left',
                'nationality_code' => 'FRA',
                'birthplace_city' => 'Lyon',
                'current_club' => 'Olympique Lyonnais U19',
                'team_since' => '2024-09-01',
                'photo' => 'https://i.pravatar.cc/400?img=68',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CB', 'CDM'],
                'modalities' => ['football'],
                'description' => 'Versatile defender, comfortable in the back line or shielding it. Strong tactical understanding.',
                'verified' => true,
                'locale' => 'fr',
                'timezone' => 'Europe/Paris',
            ],
            [
                'name' => 'Léo Moreau',
                'email' => 'leo.moreau@example.com',
                'dob' => '2009-08-09',
                'gender' => 'male',
                'height' => 173,
                'weight' => 66,
                'foot' => 'right',
                'nationality_code' => 'FRA',
                'birthplace_city' => 'Marseille',
                'current_club' => 'Olympique de Marseille Academy',
                'team_since' => '2025-02-15',
                'guardian_name' => 'Antoine Moreau',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'antoine.moreau@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=69',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['RW', 'CAM'],
                'modalities' => ['football', 'beach_soccer'],
                'description' => 'Skilful right winger from Marseille. Loves to take defenders on. Good final ball, growing into his frame.',
                'locale' => 'fr',
                'timezone' => 'Europe/Paris',
            ],

            // ─── African Players ───
            [
                'name' => 'Mamadou Diallo',
                'email' => 'mamadou.diallo@example.com',
                'dob' => '2006-03-08',
                'gender' => 'male',
                'height' => 188,
                'weight' => 82,
                'foot' => 'right',
                'nationality_code' => 'SEN',
                'birthplace_country_code' => 'SEN',
                'birthplace_city' => 'Dakar',
                'current_club' => 'Génération Foot Academy',
                'team_since' => '2023-06-15',
                'photo' => 'https://i.pravatar.cc/400?img=70',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'Towering Senegalese defender. Aerial dominance, rapid recovery pace. Already trialled by European clubs.',
                'featured' => true,
                'verified' => true,
                'locale' => 'fr',
                'timezone' => 'Africa/Dakar',
            ],
            [
                'name' => 'Kwame Asante',
                'email' => 'kwame.asante@example.com',
                'dob' => '2007-10-20',
                'gender' => 'male',
                'height' => 179,
                'weight' => 72,
                'foot' => 'right',
                'nationality_code' => 'GHA',
                'birthplace_city' => 'Accra',
                'current_club' => 'Right to Dream Academy',
                'team_since' => '2024-01-08',
                'photo' => 'https://i.pravatar.cc/400?img=71',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['CAM', 'CM'],
                'modalities' => ['football'],
                'description' => 'Creative Ghanaian midfielder. Quick feet, intelligent movement. Strong technically with both feet.',
                'verified' => true,
                'locale' => 'en',
                'timezone' => 'Africa/Accra',
            ],
            [
                'name' => 'Yassine Benali',
                'email' => 'yassine.benali@example.com',
                'dob' => '2008-06-30',
                'gender' => 'male',
                'height' => 176,
                'weight' => 70,
                'foot' => 'left',
                'nationality_code' => 'MAR',
                'birthplace_city' => 'Casablanca',
                'current_club' => 'Wydad Athletic Club',
                'team_since' => '2024-08-20',
                'photo' => 'https://i.pravatar.cc/400?img=12',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['LW'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Moroccan dribbler with flair. Beats defenders consistently, dangerous from set pieces with that left foot.',
                'locale' => 'fr',
                'timezone' => 'Africa/Casablanca',
            ],
            [
                'name' => 'Chukwuma Okafor',
                'email' => 'chukwuma.okafor@example.com',
                'dob' => '2006-11-15',
                'gender' => 'male',
                'height' => 190,
                'weight' => 84,
                'foot' => 'right',
                'nationality_code' => 'NGA',
                'birthplace_city' => 'Lagos',
                'current_club' => 'Enyimba International',
                'team_since' => '2023-07-25',
                'photo' => 'https://i.pravatar.cc/400?img=14',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'Powerful Nigerian striker. Strength, pace, finishing — has all the tools. 22 goals in 30 youth matches this season.',
                'featured' => true,
                'verified' => true,
                'locale' => 'en',
                'timezone' => 'Africa/Lagos',
            ],

            // ─── Italian, German, Dutch, English Players (compact) ───
            [
                'name' => 'Alessandro Romano',
                'email' => 'alessandro.romano@example.com',
                'dob' => '2007-08-04',
                'gender' => 'male',
                'height' => 182,
                'weight' => 76,
                'foot' => 'right',
                'nationality_code' => 'ITA',
                'birthplace_city' => 'Milan',
                'current_club' => 'AC Milan Primavera',
                'team_since' => '2024-07-10',
                'photo' => 'https://i.pravatar.cc/400?img=15',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['CM', 'CAM'],
                'modalities' => ['football'],
                'description' => 'Technical Italian midfielder. Composed under pressure, dictates tempo from deep.',
                'verified' => true,
                'locale' => 'it',
                'timezone' => 'Europe/Rome',
            ],
            [
                'name' => 'Marco Bianchi',
                'email' => 'marco.bianchi@example.com',
                'dob' => '2008-05-21',
                'gender' => 'male',
                'height' => 185,
                'weight' => 78,
                'foot' => 'right',
                'nationality_code' => 'ITA',
                'birthplace_city' => 'Rome',
                'current_club' => 'AS Roma Primavera',
                'team_since' => '2024-09-15',
                'photo' => 'https://i.pravatar.cc/400?img=16',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'Roma academy defender. Reads the game like a veteran, never rushed on the ball.',
                'locale' => 'it',
                'timezone' => 'Europe/Rome',
            ],
            [
                'name' => 'Lukas Müller',
                'email' => 'lukas.muller@example.com',
                'dob' => '2007-02-12',
                'gender' => 'male',
                'height' => 186,
                'weight' => 79,
                'foot' => 'right',
                'nationality_code' => 'DEU',
                'birthplace_city' => 'Munich',
                'current_club' => 'Bayern Munich U19',
                'team_since' => '2024-06-25',
                'photo' => 'https://i.pravatar.cc/400?img=17',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CM', 'CDM'],
                'modalities' => ['football'],
                'description' => 'Bayern academy product. Box-to-box engine, tactically excellent, scores from midfield.',
                'featured' => true,
                'verified' => true,
                'locale' => 'de',
                'timezone' => 'Europe/Berlin',
            ],
            [
                'name' => 'Felix Schmidt',
                'email' => 'felix.schmidt@example.com',
                'dob' => '2009-03-17',
                'gender' => 'male',
                'height' => 174,
                'weight' => 67,
                'foot' => 'left',
                'nationality_code' => 'DEU',
                'birthplace_city' => 'Dortmund',
                'current_club' => 'Borussia Dortmund U17',
                'team_since' => '2025-01-08',
                'guardian_name' => 'Klaus Schmidt',
                'guardian_relationship' => 'Father',
                'guardian_email' => 'klaus.schmidt@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=18',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['CAM', 'LW'],
                'modalities' => ['football'],
                'description' => 'BVB youth gem. Creative spark, set-piece specialist, growing physically fast.',
                'locale' => 'de',
                'timezone' => 'Europe/Berlin',
            ],
            [
                'name' => 'Jasper van der Berg',
                'email' => 'jasper.vanderberg@example.com',
                'dob' => '2008-09-05',
                'gender' => 'male',
                'height' => 188,
                'weight' => 78,
                'foot' => 'right',
                'nationality_code' => 'NLD',
                'birthplace_city' => 'Amsterdam',
                'current_club' => 'AFC Ajax U19',
                'team_since' => '2024-08-10',
                'photo' => 'https://i.pravatar.cc/400?img=19',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CB', 'CDM'],
                'modalities' => ['football'],
                'description' => 'Tall Dutch defender from the Ajax academy. Excellent passing range, comfortable building from the back.',
                'verified' => true,
                'locale' => 'nl',
                'timezone' => 'Europe/Amsterdam',
            ],
            [
                'name' => 'Daan de Vries',
                'email' => 'daan.devries@example.com',
                'dob' => '2007-12-28',
                'gender' => 'male',
                'height' => 180,
                'weight' => 74,
                'foot' => 'right',
                'nationality_code' => 'NLD',
                'birthplace_city' => 'Eindhoven',
                'current_club' => 'PSV U19',
                'team_since' => '2024-07-20',
                'photo' => 'https://i.pravatar.cc/400?img=20',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['RW', 'ST'],
                'modalities' => ['football'],
                'description' => 'Direct Dutch winger, fast and clever. Two-footed in front of goal.',
                'locale' => 'nl',
                'timezone' => 'Europe/Amsterdam',
            ],
            [
                'name' => 'Oliver Thompson',
                'email' => 'oliver.thompson@example.com',
                'dob' => '2008-01-19',
                'gender' => 'male',
                'height' => 183,
                'weight' => 76,
                'foot' => 'right',
                'nationality_code' => 'ENG',
                'birthplace_city' => 'London',
                'current_club' => 'Chelsea U18',
                'team_since' => '2024-08-05',
                'photo' => 'https://i.pravatar.cc/400?img=21',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['CM'],
                'modalities' => ['football'],
                'description' => 'Chelsea academy. Box-to-box midfielder with great engine, scores from second line.',
                'verified' => true,
                'locale' => 'en',
                'timezone' => 'Europe/London',
            ],
            [
                'name' => 'Harry Williams',
                'email' => 'harry.williams@example.com',
                'dob' => '2007-06-23',
                'gender' => 'male',
                'height' => 178,
                'weight' => 72,
                'foot' => 'left',
                'nationality_code' => 'ENG',
                'birthplace_city' => 'Manchester',
                'current_club' => 'Manchester City U18',
                'team_since' => '2024-07-30',
                'photo' => 'https://i.pravatar.cc/400?img=22',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['LB', 'LW'],
                'modalities' => ['football'],
                'description' => 'City academy. Marauding left-back with crossing ability. Comfortable inverted in midfield.',
                'locale' => 'en',
                'timezone' => 'Europe/London',
            ],

            // ─── More diverse players ───
            [
                'name' => 'Kenji Tanaka',
                'email' => 'kenji.tanaka@example.com',
                'dob' => '2008-04-10',
                'gender' => 'male',
                'height' => 173,
                'weight' => 68,
                'foot' => 'right',
                'nationality_code' => 'JPN',
                'birthplace_city' => 'Tokyo',
                'current_club' => 'FC Tokyo U18',
                'team_since' => '2024-04-01',
                'photo' => 'https://i.pravatar.cc/400?img=23',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['CAM', 'CM'],
                'modalities' => ['football'],
                'description' => 'Technical Japanese midfielder. Disciplined, quick passing, excellent off-ball movement.',
                'locale' => 'ja',
                'timezone' => 'Asia/Tokyo',
            ],
            [
                'name' => 'Min-jun Kim',
                'email' => 'minjun.kim@example.com',
                'dob' => '2007-08-15',
                'gender' => 'male',
                'height' => 180,
                'weight' => 73,
                'foot' => 'right',
                'nationality_code' => 'KOR',
                'birthplace_city' => 'Seoul',
                'current_club' => 'FC Seoul U18',
                'team_since' => '2024-03-15',
                'photo' => 'https://i.pravatar.cc/400?img=24',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['RW', 'ST'],
                'modalities' => ['football'],
                'description' => 'Quick Korean forward. Direct, fearless, scores wonderful goals from outside the box.',
                'verified' => true,
                'locale' => 'ko',
                'timezone' => 'Asia/Seoul',
            ],
            [
                'name' => 'Daniel Hernández',
                'email' => 'daniel.hernandez@example.com',
                'dob' => '2007-11-30',
                'gender' => 'male',
                'height' => 175,
                'weight' => 71,
                'foot' => 'right',
                'nationality_code' => 'MEX',
                'birthplace_city' => 'Mexico City',
                'current_club' => 'Club América Sub-20',
                'team_since' => '2024-01-20',
                'photo' => 'https://i.pravatar.cc/400?img=25',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CM', 'CAM'],
                'modalities' => ['football'],
                'description' => 'Mexican playmaker, calm under pressure. Strong dead-ball deliveries.',
                'locale' => 'es',
                'timezone' => 'America/Mexico_City',
            ],
            [
                'name' => 'Carlos Vargas',
                'email' => 'carlos.vargas@example.com',
                'dob' => '2006-09-12',
                'gender' => 'male',
                'height' => 184,
                'weight' => 78,
                'foot' => 'left',
                'nationality_code' => 'COL',
                'birthplace_city' => 'Bogotá',
                'current_club' => 'Millonarios FC',
                'team_since' => '2023-11-05',
                'photo' => 'https://i.pravatar.cc/400?img=26',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['LB', 'CB'],
                'modalities' => ['football'],
                'description' => 'Colombian left-back. Powerful, technical, drives forward with the ball.',
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'America/Bogota',
            ],
            [
                'name' => 'Mateo Suárez',
                'email' => 'mateo.suarez@example.com',
                'dob' => '2008-07-18',
                'gender' => 'male',
                'height' => 177,
                'weight' => 72,
                'foot' => 'right',
                'nationality_code' => 'URY',
                'birthplace_city' => 'Montevideo',
                'current_club' => 'Peñarol',
                'team_since' => '2024-05-25',
                'photo' => 'https://i.pravatar.cc/400?img=27',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'Uruguayan striker in the Cavani mould. Relentless pressing, clinical finishing.',
                'featured' => true,
                'locale' => 'es',
                'timezone' => 'America/Montevideo',
            ],

            // ─── More fillers for variety (rounds out 60 male players) ───
            ['name' => 'Eduardo Pinto', 'email' => 'eduardo.pinto@example.com', 'dob' => '2008-10-05', 'gender' => 'male', 'height' => 180, 'weight' => 75, 'foot' => 'right', 'nationality_code' => 'BRA', 'birthplace_city' => 'Florianópolis', 'current_club' => 'Avaí FC', 'team_since' => '2024-09-10', 'photo' => 'https://i.pravatar.cc/400?img=28', 'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U', 'positions' => ['CB'], 'modalities' => ['football'], 'description' => 'Solid centre-back from southern Brazil. Strong in the air, good distribution.', 'locale' => 'pt', 'timezone' => 'America/Sao_Paulo'],
            ['name' => 'Ricardo Nunes', 'email' => 'ricardo.nunes@example.com', 'dob' => '2007-05-08', 'gender' => 'male', 'height' => 173, 'weight' => 67, 'foot' => 'left', 'nationality_code' => 'BRA', 'birthplace_city' => 'Goiânia', 'current_club' => 'Goiás EC', 'team_since' => '2024-02-10', 'photo' => 'https://i.pravatar.cc/400?img=29', 'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0', 'positions' => ['LW', 'CAM'], 'modalities' => ['football', 'futsal'], 'description' => 'Skilful left-footer. Slaloming runs, deceptive pace.', 'locale' => 'pt', 'timezone' => 'America/Sao_Paulo'],
            ['name' => 'Fábio Mendes', 'email' => 'fabio.mendes@example.com', 'dob' => '2006-04-22', 'gender' => 'male', 'height' => 191, 'weight' => 84, 'foot' => 'right', 'nationality_code' => 'PRT', 'birthplace_city' => 'Funchal', 'current_club' => 'Marítimo', 'team_since' => '2023-08-08', 'photo' => 'https://i.pravatar.cc/400?img=30', 'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E', 'positions' => ['GK'], 'modalities' => ['football'], 'description' => 'Tall keeper with cat-like reflexes. Commanding presence.', 'verified' => true, 'locale' => 'pt', 'timezone' => 'Europe/Lisbon'],
            ['name' => 'Joaquín Vega', 'email' => 'joaquin.vega@example.com', 'dob' => '2009-02-14', 'gender' => 'male', 'height' => 169, 'weight' => 60, 'foot' => 'right', 'nationality_code' => 'ESP', 'birthplace_city' => 'Bilbao', 'current_club' => 'Athletic Bilbao Juvenil', 'team_since' => '2025-01-10', 'guardian_name' => 'Iñaki Vega', 'guardian_relationship' => 'Father', 'guardian_email' => 'inaki.vega@example.com', 'photo' => 'https://i.pravatar.cc/400?img=31', 'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ', 'positions' => ['CM'], 'modalities' => ['football'], 'description' => 'Basque midfielder, plays with composure beyond his years.', 'locale' => 'es', 'timezone' => 'Europe/Madrid'],
            ['name' => 'Antoine Dubois', 'email' => 'antoine.dubois@example.com', 'dob' => '2007-12-03', 'gender' => 'male', 'height' => 186, 'weight' => 80, 'foot' => 'right', 'nationality_code' => 'FRA', 'birthplace_city' => 'Bordeaux', 'current_club' => 'FC Girondins de Bordeaux', 'team_since' => '2024-01-30', 'photo' => 'https://i.pravatar.cc/400?img=32', 'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'positions' => ['CDM'], 'modalities' => ['football'], 'description' => 'Defensive midfielder, breaks up play and recycles possession smartly.', 'locale' => 'fr', 'timezone' => 'Europe/Paris'],
            ['name' => 'Theo Marchetti', 'email' => 'theo.marchetti@example.com', 'dob' => '2008-08-19', 'gender' => 'male', 'height' => 179, 'weight' => 73, 'foot' => 'right', 'nationality_code' => 'ITA', 'birthplace_city' => 'Naples', 'current_club' => 'SSC Napoli Primavera', 'team_since' => '2024-08-25', 'photo' => 'https://i.pravatar.cc/400?img=34', 'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw', 'positions' => ['RB'], 'modalities' => ['football'], 'description' => 'Modern Napoli right-back. Energetic up the flank, defensively sound.', 'locale' => 'it', 'timezone' => 'Europe/Rome'],
            ['name' => 'Maximilian Weber', 'email' => 'max.weber@example.com', 'dob' => '2007-07-25', 'gender' => 'male', 'height' => 185, 'weight' => 77, 'foot' => 'right', 'nationality_code' => 'DEU', 'birthplace_city' => 'Hamburg', 'current_club' => 'Hamburger SV U19', 'team_since' => '2024-06-20', 'photo' => 'https://i.pravatar.cc/400?img=35', 'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE', 'positions' => ['ST'], 'modalities' => ['football'], 'description' => 'Strong target striker. Holds it up, finishes with conviction.', 'locale' => 'de', 'timezone' => 'Europe/Berlin'],
            ['name' => 'Sven Andersen', 'email' => 'sven.andersen@example.com', 'dob' => '2008-03-09', 'gender' => 'male', 'height' => 188, 'weight' => 79, 'foot' => 'left', 'nationality_code' => 'NOR', 'birthplace_city' => 'Oslo', 'current_club' => 'Rosenborg BK U19', 'team_since' => '2024-04-15', 'photo' => 'https://i.pravatar.cc/400?img=36', 'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0', 'positions' => ['ST'], 'modalities' => ['football'], 'description' => 'Tall Norwegian striker, prolific in front of goal.', 'locale' => 'en', 'timezone' => 'Europe/Oslo'],
            ['name' => 'Erik Lindberg', 'email' => 'erik.lindberg@example.com', 'dob' => '2007-09-28', 'gender' => 'male', 'height' => 182, 'weight' => 76, 'foot' => 'right', 'nationality_code' => 'SWE', 'birthplace_city' => 'Stockholm', 'current_club' => 'AIK Stockholm U19', 'team_since' => '2024-02-28', 'photo' => 'https://i.pravatar.cc/400?img=37', 'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U', 'positions' => ['CM'], 'modalities' => ['football'], 'description' => 'Composed Swedish midfielder. Always available, always reliable.', 'locale' => 'en', 'timezone' => 'Europe/Stockholm'],
            ['name' => 'Marcus Johansson', 'email' => 'marcus.johansson@example.com', 'dob' => '2009-06-11', 'gender' => 'male', 'height' => 170, 'weight' => 64, 'foot' => 'right', 'nationality_code' => 'SWE', 'birthplace_city' => 'Gothenburg', 'current_club' => 'IFK Göteborg U17', 'team_since' => '2025-01-25', 'guardian_name' => 'Lars Johansson', 'guardian_relationship' => 'Father', 'guardian_email' => 'lars.johansson@example.com', 'photo' => 'https://i.pravatar.cc/400?img=38', 'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0', 'positions' => ['CAM'], 'modalities' => ['football'], 'description' => 'Promising young Swedish playmaker with quick feet.', 'locale' => 'en', 'timezone' => 'Europe/Stockholm'],
            ['name' => 'Ahmed Hassan', 'email' => 'ahmed.hassan@example.com', 'dob' => '2007-04-16', 'gender' => 'male', 'height' => 178, 'weight' => 72, 'foot' => 'right', 'nationality_code' => 'EGY', 'birthplace_city' => 'Cairo', 'current_club' => 'Al Ahly SC', 'team_since' => '2023-10-12', 'photo' => 'https://i.pravatar.cc/400?img=39', 'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E', 'positions' => ['RW', 'ST'], 'modalities' => ['football'], 'description' => 'Pacy Egyptian forward, cuts in from the right and shoots well.', 'verified' => true, 'locale' => 'en', 'timezone' => 'Africa/Cairo'],
            ['name' => 'Karim Boulares', 'email' => 'karim.boulares@example.com', 'dob' => '2008-11-22', 'gender' => 'male', 'height' => 175, 'weight' => 70, 'foot' => 'left', 'nationality_code' => 'TUN', 'birthplace_city' => 'Tunis', 'current_club' => 'Espérance ST', 'team_since' => '2024-07-18', 'photo' => 'https://i.pravatar.cc/400?img=40', 'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ', 'positions' => ['CAM'], 'modalities' => ['football', 'futsal'], 'description' => 'Creative Tunisian playmaker with futsal-trained close control.', 'locale' => 'fr', 'timezone' => 'Africa/Tunis'],
            ['name' => 'Sébastien Touré', 'email' => 'sebastien.toure@example.com', 'dob' => '2006-08-30', 'gender' => 'male', 'height' => 186, 'weight' => 81, 'foot' => 'right', 'nationality_code' => 'CIV', 'birthplace_city' => 'Abidjan', 'current_club' => 'ASEC Mimosas', 'team_since' => '2023-05-15', 'photo' => 'https://i.pravatar.cc/400?img=41', 'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'positions' => ['CDM'], 'modalities' => ['football'], 'description' => 'Powerful Ivorian midfielder. All-action style, big tackle, good distribution.', 'locale' => 'fr', 'timezone' => 'Africa/Abidjan'],
            ['name' => 'Adam Novak', 'email' => 'adam.novak@example.com', 'dob' => '2008-12-12', 'gender' => 'male', 'height' => 184, 'weight' => 78, 'foot' => 'right', 'nationality_code' => 'POL', 'birthplace_city' => 'Warsaw', 'current_club' => 'Legia Warsaw U19', 'team_since' => '2024-08-30', 'photo' => 'https://i.pravatar.cc/400?img=42', 'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw', 'positions' => ['CB'], 'modalities' => ['football'], 'description' => 'Strong Polish centre-back, aerial dominator.', 'locale' => 'en', 'timezone' => 'Europe/Warsaw'],
            ['name' => 'Luka Marković', 'email' => 'luka.markovic@example.com', 'dob' => '2007-01-08', 'gender' => 'male', 'height' => 187, 'weight' => 80, 'foot' => 'right', 'nationality_code' => 'HRV', 'birthplace_city' => 'Zagreb', 'current_club' => 'GNK Dinamo Zagreb', 'team_since' => '2024-06-30', 'photo' => 'https://i.pravatar.cc/400?img=43', 'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE', 'positions' => ['CM'], 'modalities' => ['football'], 'description' => 'Tall, technical Croatian midfielder, in the Modrić mould.', 'verified' => true, 'locale' => 'en', 'timezone' => 'Europe/Zagreb'],
            ['name' => 'Stefan Petrović', 'email' => 'stefan.petrovic@example.com', 'dob' => '2008-04-25', 'gender' => 'male', 'height' => 181, 'weight' => 75, 'foot' => 'right', 'nationality_code' => 'SRB', 'birthplace_city' => 'Belgrade', 'current_club' => 'Red Star Belgrade U19', 'team_since' => '2024-07-22', 'photo' => 'https://i.pravatar.cc/400?img=44', 'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0', 'positions' => ['CAM'], 'modalities' => ['football'], 'description' => 'Serbian creative midfielder. Visionary passes, calm under pressure.', 'locale' => 'en', 'timezone' => 'Europe/Belgrade'],
            ['name' => 'Filip Marković', 'email' => 'filip.markovic@example.com', 'dob' => '2009-07-29', 'gender' => 'male', 'height' => 172, 'weight' => 65, 'foot' => 'left', 'nationality_code' => 'SRB', 'birthplace_city' => 'Novi Sad', 'current_club' => 'FK Vojvodina U17', 'team_since' => '2025-02-20', 'guardian_name' => 'Aleksandar Marković', 'guardian_relationship' => 'Father', 'guardian_email' => 'aleksandar.markovic@example.com', 'photo' => 'https://i.pravatar.cc/400?img=45', 'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U', 'positions' => ['LW'], 'modalities' => ['football'], 'description' => 'Quick Serbian winger with terrific left foot.', 'locale' => 'en', 'timezone' => 'Europe/Belgrade'],
            ['name' => 'Bohdan Kovalenko', 'email' => 'bohdan.kovalenko@example.com', 'dob' => '2007-10-17', 'gender' => 'male', 'height' => 183, 'weight' => 76, 'foot' => 'right', 'nationality_code' => 'UKR', 'birthplace_city' => 'Kyiv', 'current_club' => 'Dynamo Kyiv U19', 'team_since' => '2024-05-08', 'photo' => 'https://i.pravatar.cc/400?img=46', 'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0', 'positions' => ['RB', 'CM'], 'modalities' => ['football'], 'description' => 'Versatile Ukrainian player, can fill multiple roles competently.', 'locale' => 'en', 'timezone' => 'Europe/Kyiv'],
            ['name' => 'Yusuf Demir', 'email' => 'yusuf.demir@example.com', 'dob' => '2008-02-21', 'gender' => 'male', 'height' => 177, 'weight' => 71, 'foot' => 'left', 'nationality_code' => 'TUR', 'birthplace_city' => 'Istanbul', 'current_club' => 'Galatasaray U19', 'team_since' => '2024-06-12', 'photo' => 'https://i.pravatar.cc/400?img=47', 'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E', 'positions' => ['LW', 'CAM'], 'modalities' => ['football'], 'description' => 'Turkish wonderkid. Dribbler, scorer, creator — does it all from the left.', 'featured' => true, 'verified' => true, 'locale' => 'en', 'timezone' => 'Europe/Istanbul'],
            ['name' => 'Tyler Brown', 'email' => 'tyler.brown@example.com', 'dob' => '2006-05-04', 'gender' => 'male', 'height' => 180, 'weight' => 74, 'foot' => 'right', 'nationality_code' => 'USA', 'birthplace_city' => 'Los Angeles', 'current_club' => 'LA Galaxy II', 'team_since' => '2023-09-10', 'photo' => 'https://i.pravatar.cc/400?img=48', 'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ', 'positions' => ['CM'], 'modalities' => ['football'], 'description' => 'American midfielder. High work rate, college recruit potential.', 'locale' => 'en', 'timezone' => 'America/Los_Angeles'],
            ['name' => 'Liam O\'Connor', 'email' => 'liam.oconnor@example.com', 'dob' => '2008-09-13', 'gender' => 'male', 'height' => 184, 'weight' => 77, 'foot' => 'left', 'nationality_code' => 'CAN', 'birthplace_city' => 'Toronto', 'current_club' => 'Toronto FC II', 'team_since' => '2024-04-20', 'photo' => 'https://i.pravatar.cc/400?img=49', 'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ', 'positions' => ['CB'], 'modalities' => ['football'], 'description' => 'Composed Canadian centre-back. Calm, two-footed in defence.', 'locale' => 'en', 'timezone' => 'America/Toronto'],
            ['name' => 'Liam Sullivan', 'email' => 'liam.sullivan@example.com', 'dob' => '2007-03-31', 'gender' => 'male', 'height' => 176, 'weight' => 70, 'foot' => 'right', 'nationality_code' => 'AUS', 'birthplace_city' => 'Sydney', 'current_club' => 'Sydney FC Academy', 'team_since' => '2024-01-12', 'photo' => 'https://i.pravatar.cc/400?img=50', 'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw', 'positions' => ['RW'], 'modalities' => ['football'], 'description' => 'Australian winger with pace and end product.', 'locale' => 'en', 'timezone' => 'Australia/Sydney'],
        ];
    }

    /**
     * 20 female players with realistic data and gender-matched photos.
     * Photos source: pravatar.cc with female-locked seeds.
     */
    private function getFemalePlayers(): array
    {
        return [
            [
                'name' => 'Sofia Martins',
                'nickname' => 'Sofi',
                'email' => 'sofia.martins@example.com',
                'dob' => '2007-06-12',
                'gender' => 'female',
                'height' => 168,
                'weight' => 58,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'São Paulo',
                'current_club' => 'Corinthians Feminino Sub-20',
                'team_since' => '2024-02-15',
                'photo' => 'https://i.pravatar.cc/400?img=1',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['CAM', 'CM'],
                'modalities' => ['football'],
                'description' => 'Creative Brazilian midfielder. Strong technique, excellent vision, set-piece specialist. Already capped at U20 national level.',
                'featured' => true,
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Camila Rodrigues',
                'email' => 'camila.rodrigues@example.com',
                'dob' => '2006-09-08',
                'gender' => 'female',
                'height' => 172,
                'weight' => 62,
                'foot' => 'left',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Rio de Janeiro',
                'current_club' => 'Flamengo Feminino',
                'team_since' => '2023-08-20',
                'photo' => 'https://i.pravatar.cc/400?img=5',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['ST', 'LW'],
                'modalities' => ['football', 'beach_soccer'],
                'description' => 'Brazilian striker with sharp instinct. Dangerous in the box, beats keepers with placement, not power.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Beatriz Costa',
                'email' => 'beatriz.costa@example.com',
                'dob' => '2008-04-19',
                'gender' => 'female',
                'height' => 165,
                'weight' => 55,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Belo Horizonte',
                'current_club' => 'Cruzeiro Feminino',
                'team_since' => '2024-06-05',
                'photo' => 'https://i.pravatar.cc/400?img=9',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['LW'],
                'modalities' => ['football'],
                'description' => 'Tricky Brazilian winger. Dribbling instincts, ability to take a defender either way.',
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Ana Beatriz Lima',
                'nickname' => 'Bia',
                'email' => 'ana.lima@example.com',
                'dob' => '2009-11-22',
                'gender' => 'female',
                'height' => 160,
                'weight' => 52,
                'foot' => 'right',
                'nationality_code' => 'BRA',
                'birthplace_city' => 'Salvador',
                'current_club' => 'EC Bahia Feminino Sub-17',
                'team_since' => '2025-01-30',
                'guardian_name' => 'Patrícia Lima',
                'guardian_relationship' => 'Mother',
                'guardian_email' => 'patricia.lima@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=10',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CAM'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Young Brazilian playmaker. Plays with maturity well beyond her years.',
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'America/Sao_Paulo',
            ],
            [
                'name' => 'Lucía González',
                'email' => 'lucia.gonzalez@example.com',
                'dob' => '2007-02-28',
                'gender' => 'female',
                'height' => 170,
                'weight' => 60,
                'foot' => 'right',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Buenos Aires',
                'current_club' => 'Boca Juniors Femenino',
                'team_since' => '2024-03-10',
                'photo' => 'https://i.pravatar.cc/400?img=20',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['CM', 'CDM'],
                'modalities' => ['football'],
                'description' => 'Argentine midfielder with serious work ethic. Wins her battles and recycles possession.',
                'featured' => true,
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Valeria Pérez',
                'email' => 'valeria.perez@example.com',
                'dob' => '2008-07-14',
                'gender' => 'female',
                'height' => 174,
                'weight' => 63,
                'foot' => 'right',
                'nationality_code' => 'ARG',
                'birthplace_city' => 'Rosario',
                'current_club' => 'River Plate Femenino',
                'team_since' => '2024-09-01',
                'photo' => 'https://i.pravatar.cc/400?img=21',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'Strong Argentine centre-back. Reads the game well, dominant in the air.',
                'locale' => 'es',
                'timezone' => 'America/Argentina/Buenos_Aires',
            ],
            [
                'name' => 'Marta Fernandes',
                'email' => 'marta.fernandes@example.com',
                'dob' => '2006-10-05',
                'gender' => 'female',
                'height' => 167,
                'weight' => 57,
                'foot' => 'left',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Lisbon',
                'current_club' => 'SL Benfica Feminino',
                'team_since' => '2023-07-15',
                'photo' => 'https://i.pravatar.cc/400?img=25',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['LW', 'ST'],
                'modalities' => ['football'],
                'description' => 'Portuguese forward with elite finishing. National team U23 captain.',
                'featured' => true,
                'verified' => true,
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],
            [
                'name' => 'Inês Carvalho',
                'email' => 'ines.carvalho@example.com',
                'dob' => '2008-12-30',
                'gender' => 'female',
                'height' => 163,
                'weight' => 54,
                'foot' => 'right',
                'nationality_code' => 'PRT',
                'birthplace_city' => 'Porto',
                'current_club' => 'FC Porto Feminino',
                'team_since' => '2024-08-08',
                'photo' => 'https://i.pravatar.cc/400?img=29',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['CAM'],
                'modalities' => ['football'],
                'description' => 'Technical Portuguese attacking midfielder. Reads the game like a chess match.',
                'locale' => 'pt',
                'timezone' => 'Europe/Lisbon',
            ],
            [
                'name' => 'Isabella García',
                'email' => 'isabella.garcia@example.com',
                'dob' => '2007-08-17',
                'gender' => 'female',
                'height' => 171,
                'weight' => 61,
                'foot' => 'right',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Madrid',
                'current_club' => 'Real Madrid Femenino B',
                'team_since' => '2024-07-01',
                'photo' => 'https://i.pravatar.cc/400?img=32',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['RB', 'CM'],
                'modalities' => ['football'],
                'description' => 'Modern Spanish fullback. Attacks and defends with equal intensity.',
                'verified' => true,
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],
            [
                'name' => 'Carmen López',
                'email' => 'carmen.lopez@example.com',
                'dob' => '2008-05-23',
                'gender' => 'female',
                'height' => 169,
                'weight' => 59,
                'foot' => 'left',
                'nationality_code' => 'ESP',
                'birthplace_city' => 'Barcelona',
                'current_club' => 'FC Barcelona Femení B',
                'team_since' => '2024-08-15',
                'photo' => 'https://i.pravatar.cc/400?img=36',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CM', 'CDM'],
                'modalities' => ['football'],
                'description' => 'La Masia graduate. Press-resistant midfielder with elite passing range.',
                'featured' => true,
                'locale' => 'es',
                'timezone' => 'Europe/Madrid',
            ],
            [
                'name' => 'Emma Laurent',
                'email' => 'emma.laurent@example.com',
                'dob' => '2007-04-09',
                'gender' => 'female',
                'height' => 173,
                'weight' => 62,
                'foot' => 'right',
                'nationality_code' => 'FRA',
                'birthplace_city' => 'Lyon',
                'current_club' => 'Olympique Lyonnais Féminin',
                'team_since' => '2024-05-20',
                'photo' => 'https://i.pravatar.cc/400?img=44',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'OL Academy striker. Cold-blooded finisher, knows where to be.',
                'featured' => true,
                'verified' => true,
                'locale' => 'fr',
                'timezone' => 'Europe/Paris',
            ],
            [
                'name' => 'Léa Rousseau',
                'email' => 'lea.rousseau@example.com',
                'dob' => '2008-11-15',
                'gender' => 'female',
                'height' => 166,
                'weight' => 57,
                'foot' => 'right',
                'nationality_code' => 'FRA',
                'birthplace_city' => 'Paris',
                'current_club' => 'Paris Saint-Germain Féminine',
                'team_since' => '2024-06-30',
                'photo' => 'https://i.pravatar.cc/400?img=45',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CAM', 'LW'],
                'modalities' => ['football'],
                'description' => 'PSG academy product. Skilful, technical, fearless in possession.',
                'locale' => 'fr',
                'timezone' => 'Europe/Paris',
            ],
            [
                'name' => 'Sophie Müller',
                'email' => 'sophie.muller@example.com',
                'dob' => '2007-01-28',
                'gender' => 'female',
                'height' => 175,
                'weight' => 64,
                'foot' => 'right',
                'nationality_code' => 'DEU',
                'birthplace_city' => 'Wolfsburg',
                'current_club' => 'VfL Wolfsburg Frauen II',
                'team_since' => '2024-03-25',
                'photo' => 'https://i.pravatar.cc/400?img=47',
                'video_url' => 'https://www.youtube.com/embed/2g811Eo7K8U',
                'positions' => ['CB'],
                'modalities' => ['football'],
                'description' => 'Tall, physical German centre-back. Aerially dominant, plays out from the back well.',
                'verified' => true,
                'locale' => 'de',
                'timezone' => 'Europe/Berlin',
            ],
            [
                'name' => 'Lena Bauer',
                'email' => 'lena.bauer@example.com',
                'dob' => '2009-03-04',
                'gender' => 'female',
                'height' => 162,
                'weight' => 53,
                'foot' => 'left',
                'nationality_code' => 'DEU',
                'birthplace_city' => 'Frankfurt',
                'current_club' => 'Eintracht Frankfurt Frauen U17',
                'team_since' => '2025-02-12',
                'guardian_name' => 'Anna Bauer',
                'guardian_relationship' => 'Mother',
                'guardian_email' => 'anna.bauer@example.com',
                'photo' => 'https://i.pravatar.cc/400?img=48',
                'video_url' => 'https://www.youtube.com/embed/9bZkp7q19f0',
                'positions' => ['LW'],
                'modalities' => ['football'],
                'description' => 'Young German winger. Quick, fearless, learning fast.',
                'locale' => 'de',
                'timezone' => 'Europe/Berlin',
            ],
            [
                'name' => 'Chiara Romano',
                'email' => 'chiara.romano@example.com',
                'dob' => '2007-07-08',
                'gender' => 'female',
                'height' => 168,
                'weight' => 58,
                'foot' => 'right',
                'nationality_code' => 'ITA',
                'birthplace_city' => 'Rome',
                'current_club' => 'AS Roma Femminile',
                'team_since' => '2024-08-12',
                'photo' => 'https://i.pravatar.cc/400?img=49',
                'video_url' => 'https://www.youtube.com/embed/L_jWHffIx5E',
                'positions' => ['CM'],
                'modalities' => ['football'],
                'description' => 'Italian midfielder. Technical, intelligent, tireless engine.',
                'verified' => true,
                'locale' => 'it',
                'timezone' => 'Europe/Rome',
            ],
            [
                'name' => 'Lotte Jansen',
                'email' => 'lotte.jansen@example.com',
                'dob' => '2008-09-21',
                'gender' => 'female',
                'height' => 174,
                'weight' => 62,
                'foot' => 'right',
                'nationality_code' => 'NLD',
                'birthplace_city' => 'Amsterdam',
                'current_club' => 'AFC Ajax Vrouwen',
                'team_since' => '2024-07-15',
                'photo' => 'https://i.pravatar.cc/400?img=24',
                'video_url' => 'https://www.youtube.com/embed/fJ9rUzIMcZQ',
                'positions' => ['CDM'],
                'modalities' => ['football'],
                'description' => 'Dutch defensive midfielder. Reads the game tactically, shields the back four.',
                'locale' => 'nl',
                'timezone' => 'Europe/Amsterdam',
            ],
            [
                'name' => 'Charlotte Smith',
                'email' => 'charlotte.smith@example.com',
                'dob' => '2007-05-16',
                'gender' => 'female',
                'height' => 170,
                'weight' => 60,
                'foot' => 'right',
                'nationality_code' => 'ENG',
                'birthplace_city' => 'Manchester',
                'current_club' => 'Manchester City Women U21',
                'team_since' => '2024-04-08',
                'photo' => 'https://i.pravatar.cc/400?img=26',
                'video_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'positions' => ['ST'],
                'modalities' => ['football'],
                'description' => 'English striker, clinical and clever. Trained in the WSL academy system.',
                'featured' => true,
                'verified' => true,
                'locale' => 'en',
                'timezone' => 'Europe/London',
            ],
            [
                'name' => 'Yuki Watanabe',
                'email' => 'yuki.watanabe@example.com',
                'dob' => '2008-02-19',
                'gender' => 'female',
                'height' => 161,
                'weight' => 52,
                'foot' => 'right',
                'nationality_code' => 'JPN',
                'birthplace_city' => 'Tokyo',
                'current_club' => 'Tokyo Verdy Beleza',
                'team_since' => '2024-04-01',
                'photo' => 'https://i.pravatar.cc/400?img=27',
                'video_url' => 'https://www.youtube.com/embed/jNQXAC9IVRw',
                'positions' => ['CAM'],
                'modalities' => ['football', 'futsal'],
                'description' => 'Japanese playmaker with futsal-honed technique. Always one step ahead.',
                'locale' => 'ja',
                'timezone' => 'Asia/Tokyo',
            ],
            [
                'name' => 'Aisha Diop',
                'email' => 'aisha.diop@example.com',
                'dob' => '2007-12-04',
                'gender' => 'female',
                'height' => 176,
                'weight' => 65,
                'foot' => 'right',
                'nationality_code' => 'SEN',
                'birthplace_city' => 'Dakar',
                'current_club' => 'AS Pikine Féminin',
                'team_since' => '2024-01-18',
                'photo' => 'https://i.pravatar.cc/400?img=28',
                'video_url' => 'https://www.youtube.com/embed/M7lc1UVf-VE',
                'positions' => ['ST', 'LW'],
                'modalities' => ['football'],
                'description' => 'Powerful Senegalese striker. Pace, strength, finishing — total package.',
                'featured' => true,
                'verified' => true,
                'locale' => 'fr',
                'timezone' => 'Africa/Dakar',
            ],
            [
                'name' => 'Lara Hansen',
                'email' => 'lara.hansen@example.com',
                'dob' => '2008-08-11',
                'gender' => 'female',
                'height' => 167,
                'weight' => 58,
                'foot' => 'right',
                'nationality_code' => 'NOR',
                'birthplace_city' => 'Oslo',
                'current_club' => 'Vålerenga Fotball Damer',
                'team_since' => '2024-05-25',
                'photo' => 'https://i.pravatar.cc/400?img=31',
                'video_url' => 'https://www.youtube.com/embed/oHg5SJYRHA0',
                'positions' => ['CM', 'CAM'],
                'modalities' => ['football'],
                'description' => 'Norwegian midfielder with great tactical sense. Strong dead-ball delivery.',
                'locale' => 'en',
                'timezone' => 'Europe/Oslo',
            ],
        ];
    }
}
